use std::error::Error;

pub async fn resolve(name_str: &str) -> Result<String, Box<dyn Error>> {

  todo!()
}